### PR TITLE
Removing notes on installing gc patched 1.8.x/1.9

### PR DESCRIPTION
**Pull request by nruth**
At time of writing this would have been useful related information, but Ruby 2 happened, and I don't think it's pertinent documentation for this gem.

### CODE REVIEW

**Comment by senny** [comment]
I'm :+1: on this change. However since `rails-perftest` still works with Rails versions that don't dictate Ruby 2.0 let's leave a small note pointing to an older revision of that README. This way people can still get to that information but we don't clutter the whole README for most users.

**Comment by nruth** [comment]
How's that? I left it in the same place with similar title incase anyone's expecting it to be in the same place. It could probably go to the bottom or something though, as it's a bit of a distraction. But fewer pages of distraction than before :)

**Comment by senny** [comment]
:+1:

**Comment by senny** [comment]
thank you :yellow_heart:

**Pull request merged**
